//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatementApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatemementComments
    {
        public int ID { get; set; }
        public Nullable<int> StatementID { get; set; }
        public string Comment { get; set; }
        public Nullable<int> CommentAuthorID { get; set; }
        public Nullable<System.DateTime> CommentTime { get; set; }
    
        public virtual Statement Statement { get; set; }
        public virtual User User { get; set; }
    }
}
